export const AuthenticationStatus = {
    LANDING: "LANDING",
    SIGNUP: "SIGNUP",
    LOGIN: "LOGIN",
    OFFER2FA: "OFFER2FA",
    COLLECT2FAPHONENUMBER: "COLLECT2FAPHONENUMBER",
    VERIFY2FA: "VERIFY2FA",
    AUTHENTICATED: "AUTHENTICATED",
}